title: Building Software Together
subtitle: "a student's guide to being a compassionate programmer"
url: https://buildtogether.tech
repository: gvwilson/bst
default_image: /static/fixme.svg

chapters:
  - slug: "introduction"
    title: "Introduction"
  - slug: "important"
    title: "The Important Stuff"
  - slug: "starting"
    title: "Getting Started"
  - slug: "teams"
    title: "Building Productive Teams"
  - slug: "10-persuade"
    title: "How to Talk People Into Things"
  - slug: "conflict"
    title: "Managing Conflict"
  - slug: "git-solo"
    title: "Using Git On Your Own"
  - slug: "git-team"
    title: "Using Git Together"
  - slug: "ip"
    title: "Intellectual Property"
  - slug: "project"
    title: "Project Structure"
  - slug: "communicate"
    title: "Communicating"
  - slug: "testing"
    title: "Is It Right Enough?"
  - slug: "design"
    title: "Software Design"
  - slug: "security"
    title: "Security"
  - slug: "errors"
    title: "When Things Go Wrong"
  - slug: "debugging"
    title: "Debugging"
  - slug: "automation"
    title: "Automation"
  - slug: "tooling"
    title: "The Tool Shapes the Hand"
  - slug: "10-comfortable"
    title: "How to Make Yourself Comfortable"
  - slug: "process"
    title: "Feedback Loops"
  - slug: "wide-world"
    title: "The Big Wide World"
  - slug: "10-newcomers"
    title: "How to Welcome Newcomers"
  - slug: "research"
    title: "A Random Sample of Research"
  - slug: "internships"
    title: "Internships"
  - slug: "rights"
    title: "Know Your Rights"
  - slug: "business"
    title: "The Business of Software"
  - slug: "10-fired"
    title: "How to Handle Being Fired"
  - slug: "delivery"
    title: "At the End of the Day"
  - slug: "10-handover"
    title: "How to Hand Over and Move On"
  - slug: "conclusion"
    title: "Conclusion"
  - appendix: true
  - slug: "license"
    title: "License"
    file: "LICENSE.md"
  - slug: "bibliography"
    title: "Bibliography"
  - slug: "conduct"
    title: "Code of Conduct"
    file: "CONDUCT.md"
  - slug: "contributing"
    title: "Contributing"
    file: "CONTRIBUTING.md"
  - slug: "glossary"
    title: "Glossary"
  - slug: "links"
    title: "Links"
  - slug: "thinking"
    title: "Thinking and Learning"
  - slug: "methods"
    title: "Research Methods"
  - slug: "novices"
    title: "Novice Programmers"
  - slug: "evaluation"
    title: "Performance Evaluation"

author:
  name: Greg Wilson
  url: third-bit.com
  email: gvwilson@third-bit.com
  github: https://github.com/gvwilson
  twitter: https://twitter.com/gvwilson
  linkedin: https://www.linkedin.com/in/greg-wilson-a26510b6/

markdown: kramdown

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter_opts:
    disable: true
  link_defs: >
    {
      "adhd-thread": ["https://twitter.com/NomeDaBarbarian/status/1369846245200515072", "A thread on ADHD"],
      "ant": ["https://ant.apache.org/", "Apache Ant"],
      "ask-a-manager": ["https://www.askamanager.org/", "Ask a Manager"],
      "automattic-hiring": ["https://automattic.com/work-with-us/how-we-hire-developers/", "Automattic hiring process"],
      "bitbucket": ["https://bitbucket.org/", "Bitbucket"],
      "black": ["https://pypi.org/project/black/", "Black"],
      "bleachbit": ["https://www.bleachbit.org/", "BleachBit"],
      "block-party": ["https://www.blockpartyapp.com/", "Block Party"],
      "bst-repo": ["https://github.com/gvwilson/buildtogether.tech/", "Building Software Together repository"],
      "buzzfeed-datacamp": ["http://third-bit.com/2019/04/22/datacamp-clarifications/", "DataCamp Clarifications"],
      "captain-awkward": ["https://www.buzzfeednews.com/article/daveyalba/datacamp-sexual-harassment-metoo-tech-startup ", "Buzzfeed article on DataCamp"],
      "carpentries-git": ["https://swcarpentry.github.io/git-novice/", "The Carpentries' lesson on Git"],
      "carpentrycon-talk": ["https://www.youtube.com/watch?v=7xR50ty5DZ0", "Greg Wilson's CarpentryCon keynote"],
      "charles-rules": ["https://geekfeminism.wikia.com/wiki/Charles%27_Rules_of_Argument", "Charles' Rules of Argument"],
      "checkstyle": ["https://checkstyle.org/", "Checkstyle"],
      "choose-license": ["https://choosealicense.com/", "Choose a License"],
      "coco-problem": ["https://coco-net.org/problem-woman-colour-nonprofit-organizations/", "The 'Problem' Woman of Colour in the Workplace"],
      "creative-commons": ["https://creativecommons.org/", "Creative Commons"],
      "contact": ["mailto:gvwilson@third-bit.com", "Contact email"],
      "contributor-covenant": ["https://www.contributor-covenant.org", "Contributor Covenant"],
      "cook-mary-rose": ["https://maryrosecook.com/", "Mary Rose Cook"],
      "cvs": ["https://www.nongnu.org/cvs/", "CVS"],
      "diagrams": ["https://www.diagrams.net/", "diagrams.net drawing tool"],
      "diffmerge": ["https://sourcegear.com/diffmerge/", "SourceGear DiffMerge"],
      "dobzhansky": ["https://en.wikipedia.org/wiki/Nothing_in_Biology_Makes_Sense_Except_in_the_Light_of_Evolution", "Nothing in biology makes sense except in the light of evolution"],
      "doi2bib": ["https://doi2bib.org/", "Turn DOIs into bibliography entries"],
      "dropbox": ["https://dropbox.com", "Dropbox"],
      "duckduckgo": ["https://duckduckgo.com/", "DuckDuckGo"],
      "eiffel": ["https://www.eiffel.org/", "Eiffel"],
      "emacs": ["https://www.gnu.org/software/emacs/", "Emacs"],
      "email": ["mailto:gvwilson@third-bit.com", "Contact address"],
      "evans-julia": ["https://jvns.ca/", "Julia Evans"],
      "evans-manager": ["https://jvns.ca/blog/things-your-manager-might-not-know/", "Things Your Manager Might Not Know"],
      "eslint": ["https://eslint.org/", "ESLint"],
      "facebook-rohingya": ["https://www.buzzfeednews.com/article/meghara/facebook-myanmar-rohingya-genocide", "How Facebook Failed the Rohingya in Myanmar"],
      "fileshredder": ["https://voidtech.net/apps/fileshredder/", "FileShredder"],
      "flower-annalee": ["https://flowerhorne.com/", "Annalee Flower"],
      "flower-good-intent": ["https://thebias.com/2017/09/26/how-good-intent-undermines-diversity-and-inclusion/", "How 'Good Intent' Undermines Diversity and Inclusion"],
      "gebru-firing": ["https://www.fastcompany.com/90608471/timnit-gebru-google-ai-ethics-equitable-tech-movement", "This is bigger than just Timnit"],
      "gender-decoder": ["http://gender-decoder.katmatfield.com/", "Gender Decoder"],
      "gendermag": ["http://gendermag.org/", "GenderMag"],
      "ghostery": ["https://www.ghostery.com/", "Ghostery"],
      "git": ["https://git-scm.com/", "Git"],
      "git-difftool": ["https://git-scm.com/docs/git-difftool", "git difftool"],
      "git-man-page-generator": ["https://git-man-page-generator.lokaltog.net/", "Git Random Man Page Generator"],
      "github": ["https://github.com/", "GitHub"],
      "github-actions": ["https://github.com/features/actions", "GitHub Actions"],
      "github-guides": ["https://guides.github.com/", "GitHub Guides"],
      "github-pages": ["https://pages.github.com/", "GitHub Pages"],
      "gitkraken": ["https://www.gitkraken.com/", "GitKraken"],
      "gitlab": ["https://gitlab.com/", "GitLab"],
      "gitlet": ["http://gitlet.maryrosecook.com/", "Gitlet"],
      "goodhart-law": ["https://en.wikipedia.org/wiki/Goodhart%27s_law", "Goodhart's Law"],
      "hanselman-dark-matter": ["https://www.hanselman.com/blog/dark-matter-developers-the-unseen-99", "Dark Matter Developers: The Unseen 99%"],
      "hippocratic-license": ["https://firstdonoharm.dev/", "Hippocratic License"],
      "jekyll": ["https://jekyllrb.com/", "Jekyll"],
      "jekyll-bug": ["https://stackoverflow.com/questions/66320774/how-to-pre-define-links-in-jekyll-config-yml-using-kramdown-links-def-options", "A bug in Jekyll"],
      "jira": ["https://www.atlassian.com/software/jira", "Jira"],
      "jsdoc": ["https://jsdoc.app/", "JSDoc"],
      "kaplan-moss-executives": ["https://jacobian.org/2021/mar/5/exec-status-update/", "How to Give a Status Update to Executives"],
      "kaplan-moss-jacob": ["https://jacobian.org/", "Jacob Kaplan-Moss"],
      "lua": ["https://www.lua.org/", "Lua"],
      "make": ["https://www.gnu.org/software/make/", "GNU Make"],
      "marthas-rules": ["https://journals.sagepub.com/doi/10.1177/088610998600100206", "Martha's Rules"],
      "mercurial": ["https://www.mercurial-scm.org/", "Mercurial"],
      "noaa-disruptive": ["https://coast.noaa.gov/ddb/", "Dealing with Disruptive Behaviors"],
      "nodejs": ["https://nodejs.org/en/", "Node.js"],
      "osi": ["https://opensource.org/", "Open Source Initiative"],
      "osi-license-list": ["https://opensource.org/licenses", "Open Source Initiative License List"],
      "pep8": ["https://www.python.org/dev/peps/pep-0008/", "PEP 8 Style Guide for Python Code"],
      "petre-marian": ["https://www.open.ac.uk/people/mp8", "Marian Petre"],
      "plantuml": ["https://plantuml.com/", "PlantUML"],
      "python": ["https://www.python.org/", "Python"],
      "pytest": ["http://pytest.org/", "pytest"],
      "pytest-benchmark": ["https://pypi.org/project/pytest-benchmark/", "pytest-benchmark"],
      "quarterback-syndrome": ["https://en.wikipedia.org/wiki/Racial_issues_faced_by_black_quarterbacks", "Quarterback syndrome"],
      "quorum": ["https://quorumlanguage.com/", "Quorum"],
      "rake": ["https://ruby.github.io/rake/", "Rake"],
      "ruby": ["https://www.ruby-lang.org/", "Ruby"],
      "scratch": ["https://scratch.mit.edu/", "Scratch"],
      "selenium": ["https://www.selenium.dev/", "Selenium"],
      "smartbear-code-review": ["https://smartbear.com/learn/code-review/best-practices-for-peer-code-review/", "Best Practices for Peer Code Review"],
      "snakemake": ["https://snakemake.readthedocs.io/en/stable/", "Snakemake"],
      "so-configure-git-editor": ["https://stackoverflow.com/questions/2596805/how-do-i-make-git-use-the-editor-of-my-choice-for-commits", "How do I make Git use the editor of my choice for commits?"],
      "so-exit-vim": ["https://stackoverflow.com/questions/11828270/how-do-i-exit-the-vim-editor", "How do I exit the Vim editor?"],
      "sourcetree": ["https://www.sourcetreeapp.com/", "SourceTree"],
      "sqlite": ["https://www.sqlite.org/", "SQLite"],
      "stack-overflow": ["https://stackoverflow.com/", "Stack Overflow"],
      "stack-overflow-good-question": ["https://stackoverflow.com/help/how-to-ask", "How do I ask a good question?"],
      "stjs": ["https://stjs.tech/", "Software Tools in JavaScript"],
      "stone-quote": ["https://twitter.com/joncstone/status/1269961630940631041", "Jon Stone on channels"],
      "subversion": ["https://subversion.apache.org/", "Subversion"],
      "t3-personas": ["https://teachtogether.tech/en/index.html#s:process-personas", "Learner Personas"],
      "tech-solidarity": ["https://techsolidarity.org/", "Tech Solidarity"],
      "thirdbit-burnout": ["http://third-bit.com/2015/11/09/daddy-why-dont-you-ever-laugh/", "Daddy, Why Don't You Ever Laugh?"],
      "tldr-gpl": ["https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)", "tl;dr summary of the GPL"],
      "tldr-legal": ["https://tldrlegal.com/", "Software Licenses in Plain English"],
      "travis-ci": ["https://travis-ci.org/", "Travis CI"],
      "udhr": ["https://en.wikipedia.org/wiki/Universal_Declaration_of_Human_Rights", "Universal Declaration of Human Rights"],
      "uk-home-office-a11y": ["https://ukhomeoffice.github.io/accessibility-posters/posters/accessibility-posters.pdf", "UK Home Office posters on accesibility"],
      "ultima-online-players": ["https://twitter.com/ZenOfDesign/status/1371347166736834560", "Number of badly-behaved players in Ultima Online"],
      "visual-basic": ["https://en.wikipedia.org/wiki/Visual_Basic", "Visual Basic"],
      "vs-code": ["https://code.visualstudio.com/", "Microsoft Visual Studio Code"],
      "wapost-facebook-vaccine": ["https://www.washingtonpost.com/technology/2021/03/14/facebook-vaccine-hesistancy-qanon/", "Massive Facebook study on users' doubt in vaccines finds a small group appears to play a big role in pushing the skepticism"],
      "webaim-wave": ["https://wave.webaim.org/", "WebAIM WAVE"],
      "womens-work": ["https://en.wikipedia.org/wiki/Women%27s_work", "Women's work"]
    }

exclude:
  - '*.sublime-*'
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - book.*
  - tmp

permalink: pretty
