- key: "ASE"
  title: "Automated Software Engineering"
- key: "CACM"
  title: "*Communications of the ACM*"
- key: "CHASE"
  title: "Cooperative and Human Aspects of Software Engineering"
- key: "CHI"
  title: "Human Factors in Computing Systems"
- key: "CSE"
  title: "*Computer Science Education*"
- key: "DLS"
  title: "Symposium on Dynamic Languages"
- key: "EASE"
  title: "Evaluation and Assessment in Software Engineering"
- key: "EDM"
  title: "Educational Data Mining"
- key: "ESE"
  title: "*Empirical Software Engineering*"
- key: "ESEC/FSE"
  title: "European Software Engineering Conference/Foundations of Software Engineering"
- key: "ESEM"
  title: "Empirical Software Engineering and Measurement"
- key: "FIE"
  title: "Frontiers in Education Conference"
- key: "FSE"
  title: "Foundations of Software Engineering"
- key: "ICER"
  title: "International Workshop on Computing Education Research"
- key: "ICPC"
  title: "International Conference on Program Comprehension"
- key: "ICSE"
  title: "International Conference on Software Engineering"
- key: "ICSE-SEET"
  title: "International Conference on Software Engineering: Software Engineering Education and Training"
- key: "ICSSP"
  title: "International Conference on Software and System Process"
- key: "ITiCSE"
  title: "Innovation and Technology in Computer Science Education"
- key: "JSS"
  title: "Journal of Systems and Software"
- key: "Koli"
  title: "Koli Calling Conference on Computing Education Research"
- key: "MSR"
  title: "International Conference on Mining Software Repositories"
- key: "OOPSLA"
  title: "Object-Oriented Programming,  Systems,  Languages,  and Applications"
- key: "PACMPL"
  title: "Proceedings of the ACM on Programming Languages"
- key: "PLATEAU"
  title: "Workshop on Evaluation and Usability of Programming Languages and Tools"
- key: "PLoS"
  title: "Public Library of Science"
- key: "PNAS"
  title: "*Proceedings of the National Academy of Sciences*"
- key: "PROMISE"
  title: "International Conference on Predictive Models in Software Engineering"
- key: "SANER"
  title: "Conference on Software Analysis, Evolution, and Reengineering"
- key: "SIGCSE"
  title: "ACM Technical Symposium on Computer Science Education"
- key: "SIGSOFT"
  title: "International Symposium on Foundations of Software Engineering"
- key: "SOSP"
  title: "Symposium on Operating Systems Principles"
- key: "SSE"
  title: "Social Software Engineering"
- key: "TCE"
  title: "*ACM Transactions on Computing Education*"
- key: "TSE"
  title: "*IEEE Transactions on Software Engineering*"
- key: "TSEM"
  title: "*ACM Transactions on Software Engineering and Methodology*"
- key: "WCRE"
  title: "Working Conference on Reverse Engineering"
